services:
  db:
    image: postgres:14
    restart: always
    container_name: postgres_planit_app_container_v1
    ports:
      - '5433:5432'
    environment:

      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: planit_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

  adminer:
    image: adminer
    container_name: adminer_planit_app_container_v1
    restart: always
    ports:
      - '8090:8080'

volumes:
  postgres-data:  # Define a volume to persist database data
