services:
  db:
    image: postgres
    restart: always
    container_name: postgres_planit_app_container
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Planit@2025
      POSTGRES_DB: planit_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

  adminer:
    image: adminer
    container_name: adminer_planit_app_container
    restart: always
    ports:
      - '8090:8080'

volumes:
  postgres-data:  # Define a volume to persist database data